### ISSUE TITLE
Auction participation flow

### ISSUE THREAD

**Issue by sashseurat** [trustlines-protocol/www.trustlines.foundation#63]
## Problem
We need a flow for users to participate in the auction. 

## Solution

- [x] @sashseurat Draft simple low-fidelity flow 

- [ ] @weilbith Review /+ @sashseurat Optimise

- [ ] Implement

## References

<img width="326" alt="Screenshot 2020-05-14 at 13 23 43" src="https://user-images.githubusercontent.com/32264127/81935139-6ce72a00-95f0-11ea-8d01-e9fabcadbc71.png">

**Comment by weilbith** [comment]
You took a shot of my shared screen? :joy:

**Comment by sashseurat** [comment]
> You took a shot of my shared screen? 😂

I should have also recorded the conversation for later 😂

**Comment by sashseurat** [comment]
A draft of the flow without pop-ups and external ux is ready for review. The text is super rough and this is to convey the idea and confirm the required basic flow.

https://www.figma.com/file/ZpTktwk2FMXnmx6e7nP2Fu/200514-auction-web-app-63?node-id=0%3A1

**Comment by weilbith** [comment]
Hey thanks for the fast draft!

My feedback is exclusively from the technical perspective.
I think you mixed up two things. There is the wallet connection the user need to accept (if he hasn't already for the merkle drop, which is kinda a requirement for this auction due to the TLN). This is basically handled by the wallet itself. So this will be automatically triggered by us as soon as the T&C have been accepted.
There could be the case that the user is visiting the page with a non-wallet enabled browser. In such a case we  need to show that as a message. But this will probably look like for the merkle drop. You can simply check that out by yourself.
The other step you possibly mixed in is the approval transaction to the TLN token contract to allow the auction contract to withdraw TLN during the bid transaction.

The spinner you used here is a different one than for the merkle drop. So I would argue to use the old one and don't start to mix them.

Else I think there is not too much need of more details. In fact we have already
the colors and many design decisions by the merkle drop components we will
definitely reuse where we can. I mean that's why we make it modular so it is
re-usable and looks consistent.
So the important stuff are your decision of the placement on the page and the
general structure. For me this would be most-likely it to be able to start.

@andfletcher any input?
   -

**Comment by sashseurat** [comment]
Had a call with @weilbith and re-did the draft with correct approve step, and added before and after steps:
https://www.figma.com/file/ZpTktwk2FMXnmx6e7nP2Fu/200514-auction-web-app-63?node-id=0%3A1

Main
![Auction Draft](https://user-images.githubusercontent.com/32264127/82030767-2994c600-9699-11ea-9bc9-a3c9de5023c8.png)

Attention, no Web3 (before):
![Attention](https://user-images.githubusercontent.com/32264127/82031135-b2136680-9699-11ea-8c1f-dd6a4befcd1a.png)

Approve
![Approve](https://user-images.githubusercontent.com/32264127/82030864-50eb9300-9699-11ea-91cf-317cf597d5bc.png)

Checking (with different spinner to save time for draft. old spinner can be used)
![Checking](https://user-images.githubusercontent.com/32264127/82030912-5f39af00-9699-11ea-846b-b1dad12d321b.png)

Bid
![Bid](https://user-images.githubusercontent.com/32264127/82030953-6eb8f800-9699-11ea-9f6c-0e16de94de4b.png)

Done (after)
![Done](https://user-images.githubusercontent.com/32264127/82030969-74aed900-9699-11ea-8b08-f1ee9a62597a.png)

**Comment by andfletcher** [comment]
> Hey thanks for the fast draft!
> 
> My feedback is exclusively from the technical perspective.
> I think you mixed up two things. There is the wallet connection the user need to accept (if he hasn't already for the merkle drop, which is kinda a requirement for this auction due to the TLN). This is basically handled by the wallet itself. So this will be automatically triggered by us as soon as the T&C have been accepted.
> There could be the case that the user is visiting the page with a non-wallet enabled browser. In such a case we need to show that as a message. But this will probably look like for the merkle drop. You can simply check that out by yourself.
> The other step you possibly mixed in is the approval transaction to the TLN token contract to allow the auction contract to withdraw TLN during the bid transaction.
> 
> The spinner you used here is a different one than for the merkle drop. So I would argue to use the old one and don't start to mix them.
> 
> Else I think there is not too much need of more details. In fact we have already
> the colors and many design decisions by the merkle drop components we will
> definitely reuse where we can. I mean that's why we make it modular so it is
> re-usable and looks consistent.
> So the important stuff are your decision of the placement on the page and the
> general structure. For me this would be most-likely it to be able to start.
> 
> ## @andfletcher any input?

No input from my side.

**Comment by berndbohmeier** [comment]
Current auction flow can be tested here https://preview.trustlines.foundation.test.beercoin.io/auction.html, let me know when you need a whitelisted address.

**Comment by berndbohmeier** [comment]
Auction flow is done
